"use client"

import { useState } from "react"
import { Brief, Plan, SSEvent } from "@/lib/types"
import { generate } from "@/lib/api"
import InputForm from "@/components/InputForm"
import StageTimeline from "@/components/StageTimeline"
import PlanView from "@/components/PlanView"
import ExportBar from "@/components/ExportBar"

const STAGES = [
  "concept",
  "bible",
  "characters",
  "episodes",
  "placements",
  "hero",
  "production_distribution",
]

export default function Home() {
  const [events, setEvents] = useState<SSEvent[]>([])
  const [plan, setPlan] = useState<Plan | null>(null)
  const [running, setRunning] = useState(false)
  const [failed, setFailed] = useState<string | null>(null)

  async function run(brief: Brief) {
    setEvents([])
    setPlan(null)
    setFailed(null)
    setRunning(true)
    try {
      await generate(brief, (e) => {
        setEvents((prev) => [...prev, e])
        if (e.type === "complete" && e.plan) setPlan(e.plan)
      })
    } catch (err) {
      setFailed(
        err instanceof Error
          ? `${err.message} — is the backend running on ${process.env.NEXT_PUBLIC_API ?? "http://localhost:8080"}?`
          : "Generation failed."
      )
    } finally {
      setRunning(false)
    }
  }

  const started = events.length > 0 || running

  return (
    <div className="relative min-h-screen">
      <main className="mx-auto max-w-6xl px-5 py-10 sm:px-8 sm:py-16">
        {/* ---- Masthead ---- */}
        <header className="mb-10 flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between">
          <div>
            <div className="mb-3 inline-flex items-center gap-2 rounded-full border border-bone-500/20 bg-ink-800/60 px-3 py-1">
              <span className="h-1.5 w-1.5 rounded-full bg-ember-400" />
              <span className="label-tech">Ashley Furniture · Branded Entertainment</span>
            </div>
            <h1 className="font-display text-4xl font-semibold leading-[0.95] tracking-tight sm:text-5xl">
              Short-Drama
              <br />
              <span className="text-ember-400">Production Workbench</span>
            </h1>
            <p className="mt-4 max-w-md font-sans text-sm leading-relaxed text-bone-300">
              A brief becomes a vertical, US-market short-drama that markets Ashley
              furniture — concept to call sheet, generated by a multi-agent pipeline.
            </p>
          </div>
          <div className="hidden text-right sm:block">
            <span className="label-tech">Aspect</span>
            <div className="ml-auto mt-1 flex h-20 w-12 items-center justify-center rounded-md border border-bone-500/25 bg-ink-800">
              <span className="font-mono text-[10px] text-bone-500">9:16</span>
            </div>
          </div>
        </header>

        {/* ---- Form ---- */}
        <div className="mb-8">
          <InputForm onSubmit={run} disabled={running} />
        </div>

        {failed && (
          <div className="mb-8 rounded-xl border border-signal-stop/40 bg-signal-stop/10 p-4">
            <p className="font-mono text-sm text-signal-stop">✕ {failed}</p>
          </div>
        )}

        {/* ---- Pipeline + Plan ---- */}
        {started && (
          <div className="mb-8">
            <StageTimeline stages={STAGES} events={events} />
          </div>
        )}

        {plan && (
          <div className="space-y-8">
            <ExportBar plan={plan} />
            <PlanView plan={plan} />
          </div>
        )}

        {!started && (
          <p className="mt-16 text-center font-mono text-xs text-bone-500">
            Lights. Camera. Brief above to roll the pipeline.
          </p>
        )}
      </main>

      <footer className="border-t border-bone-500/10 py-6 text-center">
        <span className="label-tech">
          Keyless demo mode renders a full sample plan · Set GEMINI_API_KEY for live generation
        </span>
      </footer>
    </div>
  )
}
